name: PyPi Package

on:
  push:
    tags:
    - '*'

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    env:
      PYPI_KEY: ${{secrets.PYPI_SECRET}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: Gr1N/setup-poetry@v8
      - run: make publish